### ISSUE TITLE
Make a simulation list

### ISSUE THREAD

**Issue by blootsvoets** [indodutch/sim-city-cs#2]
* [x] open a detail view from each simulation #14
* [x] create buttons or widgets to show a default output file and with style style #16
* [x] simply list all simulations #17
