### ISSUE TITLE
Glue code

### ISSUE THREAD

**Issue by c-martinez** [indodutch/sim-city-cs#4]
* [x] On submit it should take data from layer #8
* [x] webservice should send feature types and resources #18
* [x] Layer should be dynamically generated #15
* [x] Form submission should give error & success messages   (via message bus) #11

 

Using sim directive on branch (sim-form) should work together with adding data to a layer on branch (develop).
