### ISSUE TITLE
Detailed simulation view

### ISSUE THREAD

**Issue by blootsvoets** [indodutch/sim-city-cs#5]
* [x] show output files #10 
* [x] show task properties #12 
* [x] display certain output formats #13
* [x] Detail View #14
Comparable to https://github.com/NLeSC/sim-city-web/blob/master/app/tasks/viewtask.controller.js
